/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConditionalTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ROOT_VERSE"
      | "balanceOf"
      | "balanceOfBatch"
      | "combineOwnership"
      | "createPartition"
      | "createVerse"
      | "getTokenId"
      | "getVerseChildren"
      | "isApprovedForAll"
      | "isValidPartition"
      | "mintToken"
      | "owner"
      | "partitions"
      | "renounceOwnership"
      | "resolveVerse"
      | "resolvedOutcome"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "splitOwnership"
      | "supportsInterface"
      | "transferOwnership"
      | "uri"
      | "verses"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalForAll"
      | "OwnershipCombined"
      | "OwnershipSplit"
      | "OwnershipTransferred"
      | "PartitionCreated"
      | "TransferBatch"
      | "TransferSingle"
      | "URI"
      | "VerseCreated"
      | "VerseResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ROOT_VERSE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "combineOwnership",
    values: [BytesLike[], BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPartition",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createVerse",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerseChildren",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPartition",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToken",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partitions",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveVerse",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvedOutcome",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "splitOwnership",
    values: [BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "verses", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "ROOT_VERSE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "combineOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVerse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokenId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerseChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "partitions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveVerse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvedOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verses", data: BytesLike): Result;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipCombinedEvent {
  export type InputTuple = [
    user: AddressLike,
    children: BytesLike[],
    parent: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    children: string[],
    parent: string,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    children: string[];
    parent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipSplitEvent {
  export type InputTuple = [
    user: AddressLike,
    parent: BytesLike,
    children: BytesLike[],
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    parent: string,
    children: string[],
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    parent: string;
    children: string[];
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PartitionCreatedEvent {
  export type InputTuple = [parent: BytesLike, children: BytesLike[]];
  export type OutputTuple = [parent: string, children: string[]];
  export interface OutputObject {
    parent: string;
    children: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerseCreatedEvent {
  export type InputTuple = [verseId: BytesLike, parent: BytesLike];
  export type OutputTuple = [verseId: string, parent: string];
  export interface OutputObject {
    verseId: string;
    parent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerseResolvedEvent {
  export type InputTuple = [verseId: BytesLike, outcome: BytesLike];
  export type OutputTuple = [verseId: string, outcome: string];
  export interface OutputObject {
    verseId: string;
    outcome: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConditionalToken extends BaseContract {
  connect(runner?: ContractRunner | null): ConditionalToken;
  waitForDeployment(): Promise<this>;

  interface: ConditionalTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ROOT_VERSE: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  combineOwnership: TypedContractMethod<
    [children: BytesLike[], parent: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPartition: TypedContractMethod<
    [parent: BytesLike, children: BytesLike[]],
    [void],
    "nonpayable"
  >;

  createVerse: TypedContractMethod<
    [verseId: BytesLike, parent: BytesLike],
    [void],
    "nonpayable"
  >;

  getTokenId: TypedContractMethod<[verseId: BytesLike], [bigint], "view">;

  getVerseChildren: TypedContractMethod<
    [verseId: BytesLike],
    [string[]],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isValidPartition: TypedContractMethod<
    [parent: BytesLike, children: BytesLike[]],
    [boolean],
    "view"
  >;

  mintToken: TypedContractMethod<
    [to: AddressLike, verseId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  partitions: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveVerse: TypedContractMethod<
    [verseId: BytesLike, outcome: BytesLike],
    [void],
    "nonpayable"
  >;

  resolvedOutcome: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  splitOwnership: TypedContractMethod<
    [parent: BytesLike, children: BytesLike[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uri: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  verses: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, boolean] & {
        id: string;
        parent: string;
        resolved: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ROOT_VERSE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "combineOwnership"
  ): TypedContractMethod<
    [children: BytesLike[], parent: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPartition"
  ): TypedContractMethod<
    [parent: BytesLike, children: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVerse"
  ): TypedContractMethod<
    [verseId: BytesLike, parent: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenId"
  ): TypedContractMethod<[verseId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerseChildren"
  ): TypedContractMethod<[verseId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidPartition"
  ): TypedContractMethod<
    [parent: BytesLike, children: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintToken"
  ): TypedContractMethod<
    [to: AddressLike, verseId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partitions"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveVerse"
  ): TypedContractMethod<
    [verseId: BytesLike, outcome: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolvedOutcome"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "splitOwnership"
  ): TypedContractMethod<
    [parent: BytesLike, children: BytesLike[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uri"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verses"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, boolean] & {
        id: string;
        parent: string;
        resolved: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipCombined"
  ): TypedContractEvent<
    OwnershipCombinedEvent.InputTuple,
    OwnershipCombinedEvent.OutputTuple,
    OwnershipCombinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipSplit"
  ): TypedContractEvent<
    OwnershipSplitEvent.InputTuple,
    OwnershipSplitEvent.OutputTuple,
    OwnershipSplitEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PartitionCreated"
  ): TypedContractEvent<
    PartitionCreatedEvent.InputTuple,
    PartitionCreatedEvent.OutputTuple,
    PartitionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "URI"
  ): TypedContractEvent<
    URIEvent.InputTuple,
    URIEvent.OutputTuple,
    URIEvent.OutputObject
  >;
  getEvent(
    key: "VerseCreated"
  ): TypedContractEvent<
    VerseCreatedEvent.InputTuple,
    VerseCreatedEvent.OutputTuple,
    VerseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VerseResolved"
  ): TypedContractEvent<
    VerseResolvedEvent.InputTuple,
    VerseResolvedEvent.OutputTuple,
    VerseResolvedEvent.OutputObject
  >;

  filters: {
    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "OwnershipCombined(address,bytes32[],bytes32,uint256)": TypedContractEvent<
      OwnershipCombinedEvent.InputTuple,
      OwnershipCombinedEvent.OutputTuple,
      OwnershipCombinedEvent.OutputObject
    >;
    OwnershipCombined: TypedContractEvent<
      OwnershipCombinedEvent.InputTuple,
      OwnershipCombinedEvent.OutputTuple,
      OwnershipCombinedEvent.OutputObject
    >;

    "OwnershipSplit(address,bytes32,bytes32[],uint256)": TypedContractEvent<
      OwnershipSplitEvent.InputTuple,
      OwnershipSplitEvent.OutputTuple,
      OwnershipSplitEvent.OutputObject
    >;
    OwnershipSplit: TypedContractEvent<
      OwnershipSplitEvent.InputTuple,
      OwnershipSplitEvent.OutputTuple,
      OwnershipSplitEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PartitionCreated(bytes32,bytes32[])": TypedContractEvent<
      PartitionCreatedEvent.InputTuple,
      PartitionCreatedEvent.OutputTuple,
      PartitionCreatedEvent.OutputObject
    >;
    PartitionCreated: TypedContractEvent<
      PartitionCreatedEvent.InputTuple,
      PartitionCreatedEvent.OutputTuple,
      PartitionCreatedEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "URI(string,uint256)": TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;

    "VerseCreated(bytes32,bytes32)": TypedContractEvent<
      VerseCreatedEvent.InputTuple,
      VerseCreatedEvent.OutputTuple,
      VerseCreatedEvent.OutputObject
    >;
    VerseCreated: TypedContractEvent<
      VerseCreatedEvent.InputTuple,
      VerseCreatedEvent.OutputTuple,
      VerseCreatedEvent.OutputObject
    >;

    "VerseResolved(bytes32,bytes32)": TypedContractEvent<
      VerseResolvedEvent.InputTuple,
      VerseResolvedEvent.OutputTuple,
      VerseResolvedEvent.OutputObject
    >;
    VerseResolved: TypedContractEvent<
      VerseResolvedEvent.InputTuple,
      VerseResolvedEvent.OutputTuple,
      VerseResolvedEvent.OutputObject
    >;
  };
}
